### ISSUE TITLE
New argument Application:package

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/publish#10]
Implement a new argument `package` for `Application`, to automatically use the `.tview` files of the package to create the application.

**Comment by hguerra** [comment]
### TODO

- [x] New directory structure.
- [x] Application from package.
- [ ] Add legend in template. Depends on #21
- [ ] New feature: `project = {tview = "boundingBox.shp"}`.
